# This script creates #defines for raylib functions with a Raylib_ prefix
# This script was generated by an AI assistant.

import re
import sys

def extract_functions(header_path):
    defines = []

    with open(header_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Only process RLAPI function lines
            if "RLAPI" in line and "(" in line and ")" in line:
                match = re.search(r'\b([A-Za-z_][A-Za-z0-9_]*)\s*\(', line)
                if match:
                    func = match.group(1)

                    # Skip RLAPI itself if matched
                    if func != "RLAPI":
                        defines.append(f"#define Raylib_{func} {func}")

    return defines


def main():
    if len(sys.argv) < 2:
        print("Usage: python raylib_defines_gen.py raylib.h")
        return

    header = sys.argv[1]
    defines = extract_functions(header)

    for d in defines:
        print(d)


if __name__ == "__main__":
    main()
